# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/emailleadscoring',
                'doc_host': 'https://mohitshrestha.github.io',
                'git_url': 'https://github.com/mohitshrestha/emailleadscoring',
                'lib_path': 'emailleadscoring'},
  'syms': {'emailleadscoring.core': {'emailleadscoring.core.foo': ('core.html#foo', 'emailleadscoring/core.py')}}}
