# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/emailleadscoring',
                'doc_host': 'https://mohitshrestha.github.io',
                'git_url': 'https://github.com/mohitshrestha/emailleadscoring',
                'lib_path': 'emailleadscoring'},
  'syms': { 'emailleadscoring.cost_calculations': { 'emailleadscoring.cost_calculations.cost_calc_monthly_cost_table': ( 'cost_calculations.html#cost_calc_monthly_cost_table',
                                                                                                                         'emailleadscoring/cost_calculations.py'),
                                                    'emailleadscoring.cost_calculations.cost_plot_simulated_unsub_costs': ( 'cost_calculations.html#cost_plot_simulated_unsub_costs',
                                                                                                                            'emailleadscoring/cost_calculations.py'),
                                                    'emailleadscoring.cost_calculations.cost_simulate_unsub_costs': ( 'cost_calculations.html#cost_simulate_unsub_costs',
                                                                                                                      'emailleadscoring/cost_calculations.py'),
                                                    'emailleadscoring.cost_calculations.cost_total_unsub_cost': ( 'cost_calculations.html#cost_total_unsub_cost',
                                                                                                                  'emailleadscoring/cost_calculations.py')}}}
